apiVersion: v1
data:
  application.properties: |-
    spring.application.name=k8-image
    server.port=8091
    welcome.message=Hello! It is a sample Application for Google Cloud Kubernetes ConfigMap
    management.endpoints.web.exposure.include=health,info
kind: ConfigMap
metadata:
  annotations:
  name: k8-image
  namespace: default
---  